version: '3'
networks:
  app:

services:

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: db_passwd
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_passwd
      MYSQL_DATABASE: app_db
    volumes:
      - dbdata:/var/lib/mysql

  building:
    depends_on:
      - db
    build:
      dockerfile: docker/build/Dockerfile
      context: .
    volumes:
          - data-volume:/opt/maven/data

  production:
    depends_on:
      - building
    build:
      dockerfile: docker/run/Dockerfile
      context: .
    ports:
      - '8080:8080'
    volumes:
      - data-volume:/data

volumes:
  data-volume:
  dbdata:
