version: '3'
networks:
  app:

services:

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: devops12
      MYSQL_PASSWORD: secret12
      MYSQL_DATABASE: database
    volumes:
      - dbdata:/var/lib/mysql

  building:
    depends_on:
      - db
    build:
      dockerfile: docker/build/Dockerfile
      context: .
      args:
        USER: db_user
        PWD: db_passwd
        PORT: 3300
        IP: db
        DB_NAME: app_db
    volumes:
          - data-volume:/opt/maven/data

  production:
    depends_on:
      - building
    build:
      dockerfile: docker/run/Dockerfile
      context: .
    ports:
      - '8080:8080'
    volumes:
      - data-volume:/data

volumes:
  data-volume:
  dbdata:
